name: TCPrison
version: 1.0.0-SNAPSHOT
api-version: 1.16
authors:
  - SkepsonSk
  - Stoormrage

main: pl.trollcraft.prison.PrisonPlugin

soft-depend: [Vault]

commands:
  moneyDrop:
    aliases: [wyplac, banknot]